swagger: "2.0"
info:
  version: "1.0.0"
  title: Transaction API
  description: API pour gérer les transactions des utilisateurs
paths:
  /transactions/all:
    get:
      summary: Visualiser toutes les transactions d'un utilisateur
      description: Récupère toutes les transactions pour un utilisateur spécifique
      parameters:
        - in: query
          name: userId
          type: string
          required: true
          description: L'ID de l'utilisateur pour lequel récupérer les transactions
        - in: query
          name: month
          type: string
          required: false
          description: Le mois pour lequel récupérer les transactions (format YYYY-MM)
      responses:
        '200':
          description: Liste des transactions de l'utilisateur
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Requête invalide

  /transactions/{transactionId}:
    get:
      summary: Visualiser les détails d'une transaction
      description: Récupère les détails d'une transaction spécifique
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: ID de la transaction
      responses:
        '200':
          description: Détails de la transaction
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '404':
          description: Transaction non trouvée
    put:
      summary: Modifier une transaction existante
      description: Modifie les détails d'une transaction existante
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: ID de la transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Transaction modifiée avec succès
        '404':
          description: Transaction non trouvée
        '400':
          description: Requête invalide
    delete:
      summary: Supprimer une transaction
      description: Supprime une transaction spécifique
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: ID de la transaction
      responses:
        '200':
          description: Transaction supprimée avec succès
        '404':
          description: Transaction non trouvée
  /transactions:
    post:
      summary: Ajouter une nouvelle transaction
      description: Ajoute une nouvelle transaction à la liste des transactions de l'utilisateur
      parameters:
        - in: body
          name: body
          description: Nouvelle transaction à ajouter
          required: true
          schema:
            $ref: '#/definitions/NewTransaction'
      responses:
        '201':
          description: Transaction créée avec succès
        '400':
          description: Requête invalide

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: ID de la transaction
      account:
        type: string
        description: ID du compte associé à la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      amount:
        type: number
        description: Montant de la transaction
      description:
        type: string
        description: Description de la transaction
  NewTransaction:
    type: object
    properties:
      account:
        type: string
        description: ID du compte associé à la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      amount:
        type: number
        description: Montant de la transaction
      description:
        type: string
        description: Description de la transaction